Repository Vex87/Velocity-Admin, pull requests merged in 2020-09, with the labels that each got.

#19 Added command execution & response UI
  NewProject.rbxl
  src/ReplicatedStorage/Velocity.lua
  src/ServerScriptService/VelocityAdmin.server.lua
  src/StarterPlayer/StarterPlayerScripts/VelocityAdmin/AutoComplete.lua
  src/StarterPlayer/StarterPlayerScripts/VelocityAdmin/Handler.lua
  src/StarterPlayer/StarterPlayerScripts/VelocityAdmin/Input.lua
  src/StarterPlayer/StarterPlayerScripts/VelocityAdmin/Settings.lua
Labels: Type: Enhancement

#21 Changes to argument conditioning
  NewProject.rbxl
  src/ReplicatedStorage/Modules/Settings.lua
  src/ReplicatedStorage/Modules/Velocity.lua
  src/ServerScriptService/VelocityAdmin.server.lua
  src/StarterPlayer/StarterPlayerScripts/VelocityAdmin/AutoComplete.lua
  src/StarterPlayer/StarterPlayerScripts/VelocityAdmin/Handler.lua
  src/StarterPlayer/StarterPlayerScripts/VelocityAdmin/Input.lua
Labels: Priority: Critical, Type: Enhancement

#35 v0.1.1
  NewProject.rbxl
  README.md
  default.project.json
  src/Client/VelocityAdmin/Announcement.lua
  src/Client/VelocityAdmin/init.client.lua
  src/Shared/VelocityAdmin/Modules/Settings.lua
  src/Shared/VelocityAdmin/Modules/Velocity.lua
  src/Shared/VelocityAdmin/Remotes/init.meta.json
Labels: v0.1.1

#37 Revamped everything (optimizations & commands), API
  NewProject.rbxl
  default.project.json
  src/Client/VelocityAdmin/Announcement.lua
  src/Client/VelocityAdmin/AutoComplete.lua
  src/Client/VelocityAdmin/Handler.lua
  src/Client/VelocityAdmin/Input.lua
  src/Client/VelocityAdmin/init.client.lua
  src/Server/VelocityAdmin.server.lua
  src/Shared/VelocityAdmin/Modules/Commands/Fun/char.lua
  src/Shared/VelocityAdmin/Modules/Commands/Fun/hat.lua
  src/Shared/VelocityAdmin/Modules/Commands/Fun/name.lua
  src/Shared/VelocityAdmin/Modules/Commands/Fun/removehats.lua
  src/Shared/VelocityAdmin/Modules/Commands/Fun/unname.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/cleartools.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/damage.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/f3x.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/ff.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/freeze.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/god.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/heal.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/health.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/invis.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/jump.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/jumppower.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/kill.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/maxhealth.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/re.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/speed.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/sword.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/unequipall.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/unff.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/unfreeze.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/ungod.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Character/vis.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/age.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/ban.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/id.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/isfriendswith.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/isingroup.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/kick.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/pban.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/rank.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/tp.lua
  src/Shared/VelocityAdmin/Modules/Commands/Moderation_Player/unban.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/an.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/brightness.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/cancelshutdown.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/defaultcharacterloads.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/defaultjumppower.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/defaultspeed.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/lock.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/respawntime.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/shutdown.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/status.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/time.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/unlock.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/unstatus.lua
  src/Shared/VelocityAdmin/Modules/Commands/Utility/useemotes.lua
  src/Shared/VelocityAdmin/Modules/Helper.lua
Labels: Priority: Critical, v0.1.2

#38 Added 3 player args, multiple players, random, and team.
  .vscode/settings.json
  src/Shared/VelocityAdmin/Modules/Helper.lua
Labels: v0.1.2

#39 V0.1.2
  .vscode/settings.json
  src/Shared/VelocityAdmin/Modules/Helper.lua
Labels: v0.1.2

#43 Made server script into a module
  NewProject.rbxl
  default.project.json
  src/Server/VelocityAdmin/Server/Helper.lua
  src/Server/VelocityAdmin/Server/init.server.lua
  src/Server/VelocityAdmin/init.server.lua
Labels: Priority: High, Status: In Progress, Type: Bug, Type: Optimization

#44 Finished audit logs
  NewProject.rbxl
  src/Server/VelocityAdmin/Client/AuditLog.lua
  src/Server/VelocityAdmin/Client/init.client.lua
  src/Server/VelocityAdmin/Server/AuditLog.lua
  src/Server/VelocityAdmin/Server/Helper.lua
  src/Server/VelocityAdmin/Server/init.server.lua
  src/Server/VelocityAdmin/Shared/Modules/Commands/Utility/logs.lua
Labels: Priority: High, Status: In Progress, Type: Enhancement
